package generator;

import com.seedfinding.mccore.util.pos.CPos;
import dev.xpple.cubiomes.*;

import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;

/*
The blocks of a square of chunks that caves and ravines carved out (in 1.16 carved blocks at Y<=10 are lava, the
rest air), structures filled back in, or that hold water from the terrain or the underwater carvers.
 */
public class CarveRegion {
    private static final int CHUNK_BITS = 16 * 16 * 256;

    private final int minChunkX;
    private final int minChunkZ;
    private final int width;
    private final long[][] carved;
    // blocks structures placed over carved ones, and water, allocated per chunk when needed
    private final long[][] filled;
    private final long[][] water;

    CarveRegion(CPos center, int chunkRadius) {
        this.minChunkX = center.getX() - chunkRadius;
        this.minChunkZ = center.getZ() - chunkRadius;
        this.width = 2 * chunkRadius + 1;
        this.carved = new long[width * width][CHUNK_BITS / 64];
        this.filled = new long[width * width][];
        this.water = new long[width * width][];
    }

    /*
    The caves and ravines as cubiomes carves them, which only needs the structure seed. Compared against worlds
    generated by the vanilla 1.16.1 server this matched the cave and ravine air/lava below Y=49 to ~99.4%. It
    doesn't know the terrain though: vanilla skips every piece of a cave that would touch water, so next to
    rivers and oceans this carves more than the game does (VanillaCarver doesn't have that problem).
     */
    public static CarveRegion cubiomes(long structureSeed, CPos center, int chunkRadius) {
        CarveRegion region = new CarveRegion(center, chunkRadius);
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment poses = arena.allocate(Pos3List.layout());
            MemorySegment canyonConfig = arena.allocate(CanyonCarverConfig.layout());
            MemorySegment caveConfig = arena.allocate(CaveCarverConfig.layout());
            // the biomes only matter for ocean carvers, the regular cave and canyon carvers run everywhere else
            MemorySegment biomes = arena.allocate(Cubiomes.C_INT.byteSize() * 17 * 17);
            Cubiomes.getCanyonCarverConfig(Cubiomes.CANYON_CARVER(), Cubiomes.MC_1_16_1(), canyonConfig);
            Cubiomes.getCaveCarverConfig(Cubiomes.CAVE_CARVER(), Cubiomes.MC_1_16_1(), Cubiomes.desert(), caveConfig);

            for (int i = 0; i < region.width; i++) {
                for (int j = 0; j < region.width; j++) {
                    int chunkX = region.minChunkX + i;
                    int chunkZ = region.minChunkZ + j;
                    Cubiomes.createPos3List(poses, 4096);
                    Cubiomes.carveCave(structureSeed, Cubiomes.MC_1_16_1(), chunkX, chunkZ,
                            caveConfig, Cubiomes.CAVE_CARVER(), biomes, poses);
                    Cubiomes.carveCanyon(structureSeed, Cubiomes.MC_1_16_1(), chunkX, chunkZ,
                            canyonConfig, Cubiomes.CANYON_CARVER(), biomes, poses);

                    long[] bits = region.carved[i * region.width + j];
                    int size = Pos3List.size(poses);
                    MemorySegment list = Pos3List.pos3s(poses);
                    for (int k = 0; k < size; k++) {
                        MemorySegment pos = Pos3.asSlice(list, k);
                        int index = bitIndex(Pos3.x(pos), Pos3.y(pos), Pos3.z(pos));
                        bits[index >>> 6] |= 1L << index;
                    }
                    Cubiomes.freePos3List(poses);
                }
            }
        }
        return region;
    }

    public boolean isCarved(int x, int y, int z) {
        return test(carved, x, y, z);
    }

    // whether a structure was placed over this block, see fillBox and fillColumnsDown
    public boolean isFilled(int x, int y, int z) {
        return test(filled, x, y, z);
    }

    public boolean isWater(int x, int y, int z) {
        return test(water, x, y, z);
    }

    public interface BlockConsumer {
        void accept(int x, int y, int z);
    }

    public void forEachWater(BlockConsumer consumer) {
        for (int i = 0; i < width; i++) {
            for (int j = 0; j < width; j++) {
                long[] bits = water[i * width + j];
                if (bits == null) continue;
                for (int word = 0; word < bits.length; word++) {
                    for (long w = bits[word]; w != 0; w &= w - 1) {
                        int index = word << 6 | Long.numberOfTrailingZeros(w);
                        consumer.accept((minChunkX + i) << 4 | index & 15, index >>> 8, (minChunkZ + j) << 4 | index >>> 4 & 15);
                    }
                }
            }
        }
    }

    // marks a box of air made by something other than carvers
    public void carve(int x0, int y0, int z0, int x1, int y1, int z1) {
        for (int x = x0; x <= x1; x++) {
            for (int z = z0; z <= z1; z++) {
                if (!contains(x, z)) continue;
                for (int y = Math.max(y0, 0); y <= Math.min(y1, 255); y++) {
                    setCarved(x, y, z);
                }
            }
        }
    }

    // a box of solid blocks placed by a structure
    public void fillBox(int x0, int y0, int z0, int x1, int y1, int z1) {
        for (int x = x0; x <= x1; x++) {
            for (int z = z0; z <= z1; z++) {
                if (!contains(x, z)) continue;
                for (int y = Math.max(y0, 0); y <= Math.min(y1, 255); y++) {
                    fill(x, y, z);
                }
            }
        }
    }

    // fills every column of the square from topY down through air and liquid (carved blocks, which are lava below
    // Y=11, and water) until the first solid block, like StructurePiece#fillColumnDown
    public void fillColumnsDown(int minX, int minZ, int size, int topY) {
        for (int x = minX; x < minX + size; x++) {
            for (int z = minZ; z < minZ + size; z++) {
                if (!contains(x, z)) continue;
                for (int y = topY; y > 1 && (isCarved(x, y, z) || isWater(x, y, z)); y--) {
                    fill(x, y, z);
                }
            }
        }
    }

    void setCarved(int x, int y, int z) {
        set(carved, x, y, z, true);
        set(water, x, y, z, false);
    }

    void setWater(int x, int y, int z) {
        set(carved, x, y, z, false);
        set(water, x, y, z, true);
    }

    // a solid block that isn't part of a structure, like the obsidian underwater carvers leave at Y=10
    void setSolid(int x, int y, int z) {
        set(carved, x, y, z, false);
        set(water, x, y, z, false);
    }

    private void fill(int x, int y, int z) {
        setSolid(x, y, z);
        set(filled, x, y, z, true);
    }

    private boolean test(long[][] layer, int x, int y, int z) {
        if (y < 0 || y > 255 || !contains(x, z)) return false;
        long[] bits = layer[chunkIndex(x, z)];
        int index = bitIndex(x, y, z);
        return bits != null && (bits[index >>> 6] >>> index & 1L) != 0;
    }

    private void set(long[][] layer, int x, int y, int z, boolean value) {
        if (y < 0 || y > 255 || !contains(x, z)) return;
        int chunk = chunkIndex(x, z);
        int index = bitIndex(x, y, z);
        if (value) {
            if (layer[chunk] == null) layer[chunk] = new long[CHUNK_BITS / 64];
            layer[chunk][index >>> 6] |= 1L << index;
        } else if (layer[chunk] != null) {
            layer[chunk][index >>> 6] &= ~(1L << index);
        }
    }

    private int chunkIndex(int x, int z) {
        return ((x >> 4) - minChunkX) * width + (z >> 4) - minChunkZ;
    }

    public boolean contains(int x, int z) {
        int i = (x >> 4) - minChunkX;
        int j = (z >> 4) - minChunkZ;
        return i >= 0 && j >= 0 && i < width && j < width;
    }

    public int getMinChunkX() {
        return minChunkX;
    }

    public int getMinChunkZ() {
        return minChunkZ;
    }

    public int getWidth() {
        return width;
    }

    private static int bitIndex(int x, int y, int z) {
        return y << 8 | (z & 15) << 4 | (x & 15);
    }

    static {
        CubiomesInit.load();
    }
}
