package generator;

import com.seedfinding.mccore.util.pos.CPos;
import dev.xpple.cubiomes.*;

import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;

/*
Every block carved by caves and ravines in a square of chunks, computed with cubiomes. In 1.16 carved blocks at
Y<=10 are filled with lava and the rest with air. Compared against a world generated by the vanilla 1.16.1
server this matched the cave and ravine air/lava below Y=49 to ~99.4%, the rest being springs and mineshafts.
 */
public class CubiomesCarveRegion {
    private static final int CHUNK_BITS = 16 * 16 * 256;

    private final int minChunkX;
    private final int minChunkZ;
    private final int width;
    private final long[][] carved;
    // blocks structures placed over carved ones, allocated per chunk when needed
    private final long[][] filled;

    public CubiomesCarveRegion(long structureSeed, CPos center, int chunkRadius) {
        this.minChunkX = center.getX() - chunkRadius;
        this.minChunkZ = center.getZ() - chunkRadius;
        this.width = 2 * chunkRadius + 1;
        this.carved = new long[width * width][CHUNK_BITS / 64];
        this.filled = new long[width * width][];

        try (Arena arena = Arena.ofConfined()) {
            MemorySegment poses = arena.allocate(Pos3List.layout());
            MemorySegment canyonConfig = arena.allocate(CanyonCarverConfig.layout());
            MemorySegment caveConfig = arena.allocate(CaveCarverConfig.layout());
            // the biomes only matter for ocean carvers, the regular cave and canyon carvers run everywhere else
            MemorySegment biomes = arena.allocate(Cubiomes.C_INT.byteSize() * 17 * 17);
            Cubiomes.getCanyonCarverConfig(Cubiomes.CANYON_CARVER(), Cubiomes.MC_1_16_1(), canyonConfig);
            Cubiomes.getCaveCarverConfig(Cubiomes.CAVE_CARVER(), Cubiomes.MC_1_16_1(), Cubiomes.desert(), caveConfig);

            for (int i = 0; i < width; i++) {
                for (int j = 0; j < width; j++) {
                    int chunkX = minChunkX + i;
                    int chunkZ = minChunkZ + j;
                    Cubiomes.createPos3List(poses, 4096);
                    Cubiomes.carveCave(structureSeed, Cubiomes.MC_1_16_1(), chunkX, chunkZ,
                            caveConfig, Cubiomes.CAVE_CARVER(), biomes, poses);
                    Cubiomes.carveCanyon(structureSeed, Cubiomes.MC_1_16_1(), chunkX, chunkZ,
                            canyonConfig, Cubiomes.CANYON_CARVER(), biomes, poses);

                    long[] bits = carved[i * width + j];
                    int size = Pos3List.size(poses);
                    MemorySegment list = Pos3List.pos3s(poses);
                    for (int k = 0; k < size; k++) {
                        MemorySegment pos = Pos3.asSlice(list, k);
                        int index = bitIndex(Pos3.x(pos), Pos3.y(pos), Pos3.z(pos));
                        bits[index >>> 6] |= 1L << index;
                    }
                    Cubiomes.freePos3List(poses);
                }
            }
        }
    }

    public boolean isCarved(int x, int y, int z) {
        if (y < 0 || y > 255) return false;
        int i = (x >> 4) - minChunkX;
        int j = (z >> 4) - minChunkZ;
        if (i < 0 || j < 0 || i >= width || j >= width) return false;
        int index = bitIndex(x, y, z);
        return (carved[i * width + j][index >>> 6] >>> index & 1L) != 0;
    }

    // marks a box of air made by something other than carvers
    public void carve(int x0, int y0, int z0, int x1, int y1, int z1) {
        for (int x = x0; x <= x1; x++) {
            for (int z = z0; z <= z1; z++) {
                if (!contains(x, z)) continue;
                long[] bits = carved[chunkIndex(x, z)];
                for (int y = Math.max(y0, 0); y <= Math.min(y1, 255); y++) {
                    int index = bitIndex(x, y, z);
                    bits[index >>> 6] |= 1L << index;
                }
            }
        }
    }

    // whether a structure was placed over this block, see fillBox and fillColumnsDown
    public boolean isFilled(int x, int y, int z) {
        if (y < 0 || y > 255 || !contains(x, z)) return false;
        long[] bits = filled[chunkIndex(x, z)];
        int index = bitIndex(x, y, z);
        return bits != null && (bits[index >>> 6] >>> index & 1L) != 0;
    }

    // a box of solid blocks placed by a structure
    public void fillBox(int x0, int y0, int z0, int x1, int y1, int z1) {
        for (int x = x0; x <= x1; x++) {
            for (int z = z0; z <= z1; z++) {
                if (!contains(x, z)) continue;
                for (int y = Math.max(y0, 0); y <= Math.min(y1, 255); y++) {
                    fill(x, y, z);
                }
            }
        }
    }

    // fills every column of the square from topY down through carved blocks (air, or lava below Y=11) until
    // the first block that wasn't carved, like StructurePiece#fillColumnDown
    public void fillColumnsDown(int minX, int minZ, int size, int topY) {
        for (int x = minX; x < minX + size; x++) {
            for (int z = minZ; z < minZ + size; z++) {
                if (!contains(x, z)) continue;
                for (int y = topY; y > 1 && isCarved(x, y, z); y--) {
                    fill(x, y, z);
                }
            }
        }
    }

    private void fill(int x, int y, int z) {
        int chunk = chunkIndex(x, z);
        int index = bitIndex(x, y, z);
        carved[chunk][index >>> 6] &= ~(1L << index);
        if (filled[chunk] == null) filled[chunk] = new long[CHUNK_BITS / 64];
        filled[chunk][index >>> 6] |= 1L << index;
    }

    private int chunkIndex(int x, int z) {
        return ((x >> 4) - minChunkX) * width + (z >> 4) - minChunkZ;
    }

    public boolean contains(int x, int z) {
        int i = (x >> 4) - minChunkX;
        int j = (z >> 4) - minChunkZ;
        return i >= 0 && j >= 0 && i < width && j < width;
    }

    public int getMinChunkX() {
        return minChunkX;
    }

    public int getMinChunkZ() {
        return minChunkZ;
    }

    public int getWidth() {
        return width;
    }

    private static int bitIndex(int x, int y, int z) {
        return y << 8 | (z & 15) << 4 | (x & 15);
    }

    static {
        CubiomesInit.load();
    }
}
